apiVersion: apps/v1
kind: Deployment
metadata:
  name: environment-banner
  labels:
    app: environment-banner
    environment: {{ .Values.env | quote }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: environment-banner

  template:
    metadata:
      labels:
        app: environment-banner
        environment: {{ .Values.env | quote }}

      annotations:
        configmap-revision: {{ .Values.env | quote }}

    spec:
      containers:
        - name: nginx

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: environment-banner-config
                  key: environment

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}