environment       = "Prod"
bucket_name       = "my-environment-banner-prod"
state_bucket_name = "environment-banner-terraform-state"
lock_table_name   = "environment-banner-terraform-locks"
aws_region        = "ap-south-1"
github_repository = "AmarnathBheema/environment-banner"