replicaCount: 1

image:
  repository: environment-banner
  tag: "1.0"
  pullPolicy: IfNotPresent

env: Dev
buildSha: "local"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi